server:
  port: 8081

spring:
  application:
    name: traffic-duplicator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      properties:
        enable.idempotence: false

services:
  order-v1:
    url: ${ORDER_V1_URL:http://localhost:8082}
  order-v2:
    url: ${ORDER_V2_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
